import { isRecognizedStyleTopologyRequirementTag } from './equipment-requirement-tags';

export const CONFIG_OPTION_IDS = {
  genesisEnchanted: 'genesis-enchanted',
  loadedAmmo: 'loaded-ammo',
  storedSpecial: 'stored-special',
} as const;

export const REQUIREMENT_TAGS = {
  equippedWeaponSpecialAccess: 'equipped-effect:weapon-special-access',
  equippedEofSpecialAccess: 'equipped-effect:eof-special-access',
  eofStoredSpecialConfigured: 'eof-stored-special-configured',
} as const;

export const EFFECT_REF_IDS = {
  aftershock: 'aftershock',
  abyssalParasite: 'abyssal-parasite',
  biting: 'biting',
  bolgPassive: 'bolg-passive',
  caroming: 'caroming',
  crackling: 'crackling',
  conservationOfEnergy: 'conservation-of-energy',
  dracolichSet: 'dracolich-set',
  damageOverTime: 'damage-over-time',
  deathsporeProgress: 'deathspore-progress',
  demonSlayer: 'demon-slayer',
  demonSlayerActive: 'demon-slayer-active',
  dragonSlayer: 'dragon-slayer',
  dragonSlayerActive: 'dragon-slayer-active',
  equilibrium: 'equilibrium',
  equilibriumCooldown: 'equilibrium-lock',
  eliteDracolichSet: 'elite-dracolich-set',
  eofSpecialAccess: 'eof-special-access',
  eruptive: 'eruptive',
  flanking: 'flanking',
  flankingActive: 'flanking-active',
  fulArrowsHeat: 'ful-arrows-heat',
  furyOfTheSmall: 'fury-of-the-small',
  guaranteedCriticalStrikeChance: 'critical-strike-chance:+100%',
  gloomfireDarkfang: 'gloomfire-darkfang',
  heightenedSenses: 'heightened-senses',
  igneousKalKetPassive: 'igneous-kal-ket-passive',
  igneousKalXilPassive: 'igneous-kal-xil-passive',
  igneousKalZukPassive: 'igneous-kal-zuk-passive',
  impatient: 'impatient',
  invigorating: 'invigorating',
  jawsOfTheAbyssPassive: 'jaws-of-the-abyss-passive',
  lacerationBootsPassive: 'blade-master',
  tumekensLightPassive: 'purifying-light',
  tumekensLightSpecialStatus: 'lesser-purifying-light',
  terrasaurMaulPassive: 'primal-savagery',
  laniakeasSpearPassive: 'toxic-fang',
  masterworkSpearOfAnnihilationPassive: 'masterwork-spear-of-annihilation-passive',
  amHejPassive: 'am-hej-passive',
  ekZekKilPassive: 'ashen-vow',
  endlessFrost: 'endless-frost',
  frostblades: 'frostblades',
  glovesOfPassagePassive: 'enduring-ruin',
  championsRingPassive: 'crimson-strikes',
  enchantmentOfHeroism: 'enchantment-of-heroism',
  vestmentsOfHavocSet: 'vestments-of-havoc-set',
  precise: 'precise',
  quiverPassive: 'quiver-passive',
  shadowImbuedHitAdrenaline: 'ranged-hit-adrenaline:+5%',
  ultimatums: 'ultimatums',
  undeadSlayer: 'undead-slayer',
  undeadSlayerActive: 'undead-slayer-active',
  vigourPassive: 'vigour-passive',
  warpedGemSpecialCostReduction: 'warped-gem-special-cost-reduction',
  weaponSpecialAccess: 'weapon-special-access',
  weaponClassCrossbow: 'weapon-class:crossbow',
  weaponSpecialBalanceByForce: 'weapon-special:balance-by-force',
  weaponSpecialGravitate: 'weapon-special:gravitate',
  weaponSpecialSliceAndDice: 'weapon-special:slice-and-dice',
  weaponSpecialSplitSoul: 'weapon-special:split-soul',
  weaponSpecialTheFinalFlurry: 'weapon-special:the-final-flurry',
  weaponSpecialShadowfall: 'weapon-special:shadowfall',
} as const;

const EXACT_EFFECT_REFS = new Set<string>([
  ...Object.values(EFFECT_REF_IDS),
  'amulet-of-souls-passive',
  'adrenaline-potion-cooldown',
  'adrenaline-renewal',
  'affliction',
  'anguish',
  'augury',
  'berserkers-fury',
  'binding-shot-bind',
  'blessing-of-het',
  'corruption-shot',
  'dazing-shot',
  'deathspore-cooldown',
  'deathspore-free-cast',
  'deaths-swiftness',
  'death-ward',
  'desolation',
  'divine-rage',
  'demoralise',
  EFFECT_REF_IDS.dracolichSet,
  'eclipsed-soul-heal',
  EFFECT_REF_IDS.eliteDracolichSet,
  'elite-sirenic-set',
  EFFECT_REF_IDS.aftershock,
  EFFECT_REF_IDS.biting,
  EFFECT_REF_IDS.caroming,
  EFFECT_REF_IDS.crackling,
  'font-of-life',
  'fragmentation-shot-bleed',
  EFFECT_REF_IDS.fulArrowsHeat,
  'greater-dazing-shot',
  'greater-deaths-swiftness',
  'greater-ricochet',
  'hexhunter-passive',
  EFFECT_REF_IDS.demonSlayer,
  EFFECT_REF_IDS.demonSlayerActive,
  EFFECT_REF_IDS.dragonSlayer,
  EFFECT_REF_IDS.dragonSlayerActive,
  EFFECT_REF_IDS.equilibrium,
  EFFECT_REF_IDS.equilibriumCooldown,
  EFFECT_REF_IDS.eruptive,
  EFFECT_REF_IDS.flanking,
  EFFECT_REF_IDS.flankingActive,
  EFFECT_REF_IDS.impatient,
  EFFECT_REF_IDS.invigorating,
  'incendiary-shot',
  'jas-dragonbane-arrows',
  'masterwork-ranged-set',
  'needle-strike-buff',
  'perfect-equilibrium-status',
  'piercing-shot',
  EFFECT_REF_IDS.precise,
  'rapid-fire-channel',
  'reaper-necklace-passive',
  'rigour',
  'ring-of-death-adrenaline',
  'rout',
  'salt-the-wound',
  'scripture-of-ful',
  'scripture-of-jas',
  'searing-winds',
  'shadow-imbued',
  'split-soul',
  'shadow-tendrils',
  'shadows-grace',
  'sirenic-set',
  'tight-bindings',
  'torment',
  EFFECT_REF_IDS.ultimatums,
  EFFECT_REF_IDS.undeadSlayer,
  EFFECT_REF_IDS.undeadSlayerActive,
  EFFECT_REF_IDS.vigourPassive,
  EFFECT_REF_IDS.warpedGemSpecialCostReduction,
  EFFECT_REF_IDS.weaponClassCrossbow,
  'vulnerability-bomb',
  'wen-arrows-icy-chill',
]);

const PARAMETERIZED_EFFECT_REF_PREFIXES = [
  'basic-adrenaline:',
  'critical-strike-chance:',
  'critical-strike-damage:',
  'target-damage-taken:',
  'eof-',
  'hit-chance:',
  'magic-damage-multiplier:',
  'melee-damage-multiplier:',
  'overload-tier-',
  'perfect-equilibrium-threshold:',
  'piercing-shot-snipe-reduction:',
  'ranged-critical-strike-chance:',
  'ranged-damage-multiplier:',
  'ranged-hit-adrenaline:',
  'ranged-hit-flat-bonus-ability-damage:',
  'weapon-special:',
] as const;

export function isRecognizedEffectRef(effectRef: string): boolean {
  return (
    EXACT_EFFECT_REFS.has(effectRef) ||
    PARAMETERIZED_EFFECT_REF_PREFIXES.some((prefix) => effectRef.startsWith(prefix))
  );
}

export function isRecognizedRequirementTag(tag: string): boolean {
  return (
    isRecognizedStyleTopologyRequirementTag(tag) ||
    tag === REQUIREMENT_TAGS.equippedWeaponSpecialAccess ||
    tag === REQUIREMENT_TAGS.equippedEofSpecialAccess ||
    tag === REQUIREMENT_TAGS.eofStoredSpecialConfigured ||
    tag.startsWith('eof-special:') ||
    tag.startsWith('equipped-effect:')
  );
}
