export interface SampleGameDataManifest {
  items: string[];
  abilities: string[];
  buffs: string[];
  eofSpecs: string[];
  perks: string[];
  relics: string[];
}

export const sampleGameDataManifest: SampleGameDataManifest = {
  items: [
    '/game-data/items/bolg.sample.json',
    '/game-data/items/masterwork-bow.sample.json',
    '/game-data/items/masterwork-ranged-cowl.sample.json',
    '/game-data/items/masterwork-ranged-body.sample.json',
    '/game-data/items/masterwork-ranged-chaps.sample.json',
    '/game-data/items/masterwork-ranged-vambraces.sample.json',
    '/game-data/items/masterwork-ranged-boots.sample.json',
    '/game-data/items/deathspore-arrows.sample.json',
    '/game-data/items/ful-arrows.sample.json',
    '/game-data/items/wen-arrows.sample.json',
    '/game-data/items/jas-dragonbane-arrows.sample.json',
    '/game-data/items/pernixs-quiver.sample.json',
    '/game-data/items/hexhunter-bow.sample.json',
    '/game-data/items/gloomfire-bow.sample.json',
    '/game-data/items/eldritch-crossbow.sample.json',
    '/game-data/items/seren-godbow.sample.json',
    '/game-data/items/bakriminel-bolts.sample.json',
    '/game-data/items/dracolich-coif.sample.json',
    '/game-data/items/dracolich-hauberk.sample.json',
    '/game-data/items/dracolich-chaps.sample.json',
    '/game-data/items/dracolich-vambraces.sample.json',
    '/game-data/items/dracolich-boots.sample.json',
    '/game-data/items/elite-dracolich-helm.sample.json',
    '/game-data/items/elite-dracolich-hauberk.sample.json',
    '/game-data/items/elite-dracolich-chaps.sample.json',
    '/game-data/items/elite-dracolich-vambraces.sample.json',
    '/game-data/items/elite-dracolich-boots.sample.json',
    '/game-data/items/sirenic-mask.sample.json',
    '/game-data/items/sirenic-hauberk.sample.json',
    '/game-data/items/sirenic-chaps.sample.json',
    '/game-data/items/elite-sirenic-mask.sample.json',
    '/game-data/items/elite-sirenic-hauberk.sample.json',
    '/game-data/items/elite-sirenic-chaps.sample.json',
    '/game-data/items/nightmare-gauntlets.sample.json',
    '/game-data/items/fleeting-boots.sample.json',
    '/game-data/items/tokhaar-kal-xil.sample.json',
    '/game-data/items/igneous-kal-xil.sample.json',
    '/game-data/items/igneous-kal-zuk.sample.json',
    '/game-data/items/stalkers-ring.sample.json',
    '/game-data/items/reavers-ring.sample.json',
    '/game-data/items/ring-of-death.sample.json',
    '/game-data/items/ring-of-vigour.sample.json',
    '/game-data/items/luck-of-the-dwarves.sample.json',
    '/game-data/items/essence-of-finality.sample.json',
    '/game-data/items/amulet-of-souls.sample.json',
    '/game-data/items/reaper-necklace.sample.json',
    '/game-data/items/scripture-of-ful.sample.json',
    '/game-data/items/scripture-of-jas.sample.json',
  ],
  abilities: [
    '/game-data/abilities/ranged.sample.json',
    '/game-data/abilities/binding-shot.sample.json',
    '/game-data/abilities/greater-ricochet.sample.json',
    '/game-data/abilities/galeshot.sample.json',
    '/game-data/abilities/piercing-shot.sample.json',
    '/game-data/abilities/ricochet.sample.json',
    '/game-data/abilities/snap-shot.sample.json',
    '/game-data/abilities/snipe.sample.json',
    '/game-data/abilities/bombardment.sample.json',
    '/game-data/abilities/rapid-fire.sample.json',
    '/game-data/abilities/corruption-shot.sample.json',
    '/game-data/abilities/shadow-tendrils.sample.json',
    '/game-data/abilities/imbue-shadows.sample.json',
    '/game-data/abilities/deadshot.sample.json',
    '/game-data/abilities/deaths-swiftness.sample.json',
    '/game-data/abilities/weapon-special-attack.sample.json',
    '/game-data/abilities/essence-of-finality.sample.json',
  ],
  buffs: [
    '/game-data/buffs/feasting-spores-ready.sample.json',
    '/game-data/buffs/feasting-spores-cooldown.sample.json',
    '/game-data/buffs/deaths-swiftness.sample.json',
    '/game-data/buffs/balance-by-force.sample.json',
    '/game-data/buffs/searing-winds.sample.json',
    '/game-data/buffs/shadow-imbued.sample.json',
    '/game-data/buffs/split-soul.sample.json',
    '/game-data/buffs/dracolich-infusion.sample.json',
    '/game-data/buffs/elite-dracolich-infusion.sample.json',
    '/game-data/buffs/desolation.sample.json',
    '/game-data/buffs/rigour.sample.json',
    '/game-data/buffs/anguish.sample.json',
    '/game-data/buffs/eclipsed-soul.sample.json',
    '/game-data/buffs/divine-rage.sample.json',
    '/game-data/buffs/vulnerability-bomb-area.sample.json',
    '/game-data/buffs/vulnerability.sample.json',
    '/game-data/buffs/warped-gem.sample.json',
    '/game-data/buffs/dragon-slayer-active.sample.json',
    '/game-data/buffs/demon-slayer-active.sample.json',
    '/game-data/buffs/equilibrium-cooldown.sample.json',
    '/game-data/buffs/undead-slayer-active.sample.json',
    '/game-data/buffs/flanking-active.sample.json',
    '/game-data/buffs/overload-tier-15-3.sample.json',
    '/game-data/buffs/overload-tier-15-4.sample.json',
    '/game-data/buffs/overload-tier-16-4.sample.json',
    '/game-data/buffs/overload-tier-17-5.sample.json',
  ],
  eofSpecs: [
    '/game-data/eof-specs/dark-bow-eof.sample.json',
    '/game-data/eof-specs/eldritch-crossbow-eof.sample.json',
    '/game-data/eof-specs/gloomfire-bow-eof.sample.json',
    '/game-data/eof-specs/seren-godbow-eof.sample.json',
  ],
  perks: [
    '/game-data/perks/aftershock.sample.json',
    '/game-data/perks/biting.sample.json',
    '/game-data/perks/caroming.sample.json',
    '/game-data/perks/crackling.sample.json',
    '/game-data/perks/demon-slayer.sample.json',
    '/game-data/perks/dragon-slayer.sample.json',
    '/game-data/perks/equilibrium.sample.json',
    '/game-data/perks/eruptive.sample.json',
    '/game-data/perks/flanking.sample.json',
    '/game-data/perks/impatient.sample.json',
    '/game-data/perks/invigorating.sample.json',
    '/game-data/perks/precise.sample.json',
    '/game-data/perks/ultimatums.sample.json',
    '/game-data/perks/undead-slayer.sample.json',
  ],
  relics: [
    '/game-data/relics/fury-of-the-small.sample.json',
    '/game-data/relics/berserkers-fury.sample.json',
    '/game-data/relics/blessing-of-het.sample.json',
    '/game-data/relics/font-of-life.sample.json',
    '/game-data/relics/conservation-of-energy.sample.json',
    '/game-data/relics/shadows-grace.sample.json',
    '/game-data/relics/heightened-senses.sample.json',
    '/game-data/relics/death-ward.sample.json',
  ],
};
